#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libavif
Version  : 0.9.0
Release  : 1
URL      : https://github.com/AOMediaCodec/libavif/archive/refs/tags/v0.9.0.tar.gz
Source0  : https://github.com/AOMediaCodec/libavif/archive/refs/tags/v0.9.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: libavif-lib = %{version}-%{release}
Requires: libavif-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(SvtAv1Enc)
BuildRequires : pkgconfig(dav1d)
BuildRequires : zlib-dev

%description
# libavif [![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/github/louquillio/libavif?branch=master&svg=true)](https://ci.appveyor.com/project/louquillio/libavif) [![Travis Build Status](https://travis-ci.com/AOMediaCodec/libavif.svg?branch=master)](https://travis-ci.com/AOMediaCodec/libavif)

%package dev
Summary: dev components for the libavif package.
Group: Development
Requires: libavif-lib = %{version}-%{release}
Provides: libavif-devel = %{version}-%{release}
Requires: libavif = %{version}-%{release}

%description dev
dev components for the libavif package.


%package lib
Summary: lib components for the libavif package.
Group: Libraries
Requires: libavif-license = %{version}-%{release}

%description lib
lib components for the libavif package.


%package license
Summary: license components for the libavif package.
Group: Default

%description license
license components for the libavif package.


%prep
%setup -q -n libavif-0.9.0
cd %{_builddir}/libavif-0.9.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1632332029
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1632332029
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libavif
cp %{_builddir}/libavif-0.9.0/LICENSE %{buildroot}/usr/share/package-licenses/libavif/c0804ca36a057a6cb6d65c65f7ed77decef39c97
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/avif/avif.h
/usr/lib64/cmake/libavif/libavif-config-relwithdebinfo.cmake
/usr/lib64/cmake/libavif/libavif-config-version.cmake
/usr/lib64/cmake/libavif/libavif-config.cmake
/usr/lib64/libavif.so
/usr/lib64/pkgconfig/libavif.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libavif.so.10
/usr/lib64/libavif.so.10.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libavif/c0804ca36a057a6cb6d65c65f7ed77decef39c97
